### ISSUE TITLE
To-Do / To Fix

### ISSUE THREAD

**Issue by awgybop1** [MihaiChirculete/WorldGuard#56]
- * Add a ~0.2 second delay to right-clicking since sometimes one click registers at two.

- * Redo region priority; don't exempt all other regions, instead just override their flags.

- * Enderpearls can be used to teleport into regions with enderpearls denied.

- * GameMode update packet for Adventure Mode is not sent when their gamemode is changed by a region, causing their normal Survival HUD to still show.

- + Add a database to store and re-give any effects on a player that are overwritten by WG when a player enters a region, upon leaving.

**Comment by suerion** [comment]
- [ ] - Code Cleaning
- [ ] - Issues resolving with mcpe 1.16
- [ ] - Global Regions automatically created with an world and with prefix name and config for this worlds.
- [ ] - Safe Zone, Region where Entitys, don‘t could enter. Spawn of Survival Worlds. 
- [ ] - Adding API for easier importing Plugins.

**Comment by suerion** [comment]
We should close this To-Do / To Fix and start an new Conversation
